import React from "react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { ChevronLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-teal-900 to-emerald-900">
      <div className="max-w-lg mx-auto px-4 pb-24 pt-4">
        <div className="flex items-center gap-4 mb-8">
          <Link
            to={createPageUrl("Settings")}
            className="w-10 h-10 rounded-xl bg-white/10 backdrop-blur-sm border border-white/20 flex items-center justify-center"
          >
            <ChevronLeft size={20} className="text-white" />
          </Link>
          <h1 className="text-2xl font-bold text-white">Terms of Service</h1>
        </div>

        <div className="rounded-3xl p-6 bg-white/10 backdrop-blur-xl border border-white/20 space-y-6 text-white/80 text-sm leading-relaxed">
          
          {/* 1. Service Description */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">1. Service Description</h2>
            <p>Balancen is an AI-powered fitness and wellness tracking application designed to help users monitor their nutrition, track workouts, maintain streaks, and receive personalized health suggestions. The app uses artificial intelligence to analyze food photos, estimate nutritional content, and generate customized meal and workout plans.</p>
          </div>

          {/* 2. Disclaimer of Medical Advice */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">2. Disclaimer of Medical Advice</h2>
            <div className="space-y-2">
              <p><strong>NOT MEDICAL OR PROFESSIONAL ADVICE:</strong> Balancen is a general wellness tool and does not provide medical, nutritional, or professional fitness advice. The recommendations and insights generated by the app are for informational and motivational purposes only.</p>
              <p>Do not use Balancen as a substitute for professional medical consultation. Always consult with a licensed healthcare provider, registered dietitian, or certified fitness professional before making significant changes to your diet or exercise routine.</p>
              <p>Balancen's nutritional estimates are AI-generated approximations and may not be 100% accurate. Actual nutritional content varies based on preparation methods, ingredients, and portion sizes.</p>
            </div>
          </div>

          {/* 3. User Responsibilities */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">3. User Responsibilities</h2>
            <div className="space-y-2">
              <p>You are responsible for:</p>
              <ul className="space-y-1 pl-4 list-disc list-inside">
                <li>Maintaining the confidentiality of your account credentials</li>
                <li>Providing accurate information during registration and profile setup</li>
                <li>Promptly reporting unauthorized account access</li>
                <li>Using the app in accordance with all applicable laws and regulations</li>
                <li>Not uploading offensive, illegal, or misleading content</li>
              </ul>
            </div>
          </div>

          {/* 4. Subscription Plans & Pricing */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">4. Subscription Plans & Pricing</h2>
            <div className="space-y-2">
              <p><strong>Available Plans:</strong></p>
              <ul className="space-y-1 pl-4 list-disc list-inside">
                <li>7-day free trial (full feature access)</li>
                <li>Monthly subscription (auto-renews monthly)</li>
                <li>Annual subscription (auto-renews yearly)</li>
              </ul>
              <p className="mt-2">Pricing is displayed before purchase and may vary based on location and currency. All prices are in EUR unless otherwise specified.</p>
            </div>
          </div>

          {/* 5. Free Trial & Auto-Renewal */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">5. Free Trial & Auto-Renewal</h2>
            <div className="space-y-2">
              <p><strong>Trial Period:</strong> A 7-day free trial is provided to new users with full access to premium features.</p>
              <p><strong>Auto-Renewal:</strong> At the end of the trial period, your subscription will automatically renew unless canceled at least 24 hours before the renewal date.</p>
              <p><strong>Billing:</strong> Payment will be charged to your Apple ID account on the renewal date. Charges will recur at the same frequency and price unless changed or canceled.</p>
              <p><strong>Cancellation:</strong> To cancel or manage your subscription, go to your device Settings → [Your Name] → Subscriptions → Balancen → Cancel. You can cancel anytime, but refunds are not provided for partial billing periods.</p>
            </div>
          </div>

          {/* 6. Refund Policy */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">6. Refund Policy</h2>
            <p>Refunds are governed by Apple's App Store policies. For requests regarding trial cancellations or refunds, please contact Apple Support directly. Refunds for full billing periods that have already been used are not provided.</p>
          </div>

          {/* 7. Limitation of Liability */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">7. Limitation of Liability</h2>
            <div className="space-y-2">
              <p><strong>AS-IS BASIS:</strong> Balancen is provided "as is" without warranties of any kind, express or implied. We do not guarantee specific fitness results, weight loss, or health outcomes.</p>
              <p><strong>LIABILITY CAP:</strong> To the fullest extent permitted by law, Balancen's liability for any damages arising from your use of the service is limited to the amount you paid for your subscription.</p>
              <p><strong>NO RESPONSIBILITY:</strong> Balancen is not responsible for injuries, health complications, or adverse effects resulting from following app recommendations. Always consult healthcare professionals.</p>
            </div>
          </div>

          {/* 8. Acceptable Use */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">8. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="space-y-1 pl-4 list-disc list-inside">
              <li>Use the app for illegal purposes or in violation of any laws</li>
              <li>Harass, abuse, or discriminate against other users</li>
              <li>Attempt to gain unauthorized access to the app or user accounts</li>
              <li>Reverse-engineer or decompile the app or server code</li>
              <li>Upload malware, spam, or harmful content</li>
              <li>Violate intellectual property rights</li>
              <li>Impersonate another person or entity</li>
            </ul>
          </div>

          {/* 9. Intellectual Property */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">9. Intellectual Property</h2>
            <p>All content in Balancen, including code, design, graphics, logos, and text, is the intellectual property of Balancen and protected by copyright law. You are granted a limited license to use the app for personal, non-commercial purposes. You may not reproduce, distribute, or transmit any content without our written permission.</p>
          </div>

          {/* 10. Termination of Service */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">10. Termination of Service</h2>
            <p>We reserve the right to suspend or terminate your account if you violate these Terms of Service or engage in harmful, illegal, or abusive behavior. Upon termination, you will lose access to your account and associated data. For violations, we will provide notice when possible.</p>
          </div>

          {/* 11. Changes to Terms */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">11. Changes to Terms</h2>
            <p>We may update these Terms of Service at any time. Significant changes will be communicated via email or in-app notification. Your continued use of Balancen after changes constitutes acceptance of the updated terms.</p>
          </div>

          {/* 12. Governing Law */}
          <div>
            <h2 className="text-lg font-semibold text-white mb-3">12. Governing Law</h2>
            <p>These Terms of Service are governed by the laws of Belgium. Any disputes arising from these terms or your use of Balancen shall be resolved in the courts of Belgium.</p>
          </div>

          {/* Contact */}
          <div className="bg-teal-500/20 border border-teal-500/40 rounded-xl p-4 mt-6">
            <p className="text-teal-300 font-semibold mb-2">Questions About These Terms?</p>
            <p>For questions or clarifications about these Terms of Service, please contact us at:</p>
            <p className="text-teal-300 font-semibold mt-2">hello@balancen.app</p>
            <p className="text-xs text-white/60 mt-2">Last updated: April 2026</p>
          </div>
        </div>
      </div>
    </div>
  );
}