import React, { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { useAppState } from "@/components/AppStateContext";
import { useTranslation } from "@/components/TranslationProvider";
import { useNavigate } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { Dumbbell, TrendingUp, Calendar, Zap, ArrowLeft, Plus, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { toast } from "sonner";

export default function TrainerDashboard() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { user, profile } = useAppState();
  const { t } = useTranslation();
  const [selectedPlan, setSelectedPlan] = useState(null);

  const isPremium = profile?.is_premium || profile?.role === 'owner' || profile?.role === 'collaborator';

  if (!isPremium) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-900 to-purple-900 flex flex-col items-center justify-center p-6 pb-24">
        <div className="w-20 h-20 rounded-full bg-indigo-500/20 flex items-center justify-center mb-6">
          <Zap size={40} className="text-indigo-400" />
        </div>
        <h2 className="text-white text-2xl font-bold mb-2">{t('trainer_premium_title') || 'AI Trainer — Premium'}</h2>
        <p className="text-white/70 text-center mb-8">{t('trainer_premium_desc') || 'Access personalized workout plans, session tracking and progression analysis'}</p>
        <Button
          onClick={() => navigate(createPageUrl('Premium'))}
          className="bg-gradient-to-r from-indigo-500 to-purple-500 hover:from-indigo-600 hover:to-purple-600 text-white font-bold px-8 py-3"
        >
          {t('upgrade_now') || 'Upgrade to Premium'}
        </Button>
      </div>
    );
  }

  const { data: workoutPlans = [] } = useQuery({
    queryKey: ["workout-plans", user?.email],
    queryFn: () => base44.entities.WorkoutPlan.filter({ user_email: user?.email }, "-created_date"),
    enabled: !!user?.email,
  });

  const { data: sessions = [] } = useQuery({
    queryKey: ["workout-sessions", user?.email],
    queryFn: () => base44.entities.WorkoutSession.filter({ created_by: user.email }, "-date", 30),
    enabled: !!user?.email,
  });

  const generatePlanMutation = useMutation({
    mutationFn: async (data) => {
      const response = await base44.functions.invoke('aiWorkoutGenerator', {
        profile: { ...profile, email: user.email },
        ...data,
      });
      return response.data;
    },
    onSuccess: (plan) => {
      toast.success(t('plan_generated') || 'Plan generated by AI');
      queryClient.invalidateQueries({ queryKey: ["workout-plans"] });
      setSelectedPlan(plan);
    },
    onError: () => toast.error(t('plan_error') || 'Error generating plan'),
  });

  const activatePlanMutation = useMutation({
    mutationFn: (planId) =>
      base44.entities.WorkoutPlan.update(planId, { status: "active" }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["workout-plans"] });
      toast.success(t('plan_activated') || 'Plan activated');
    },
  });

  // Calculate progression metrics
  const volumeData = sessions
    .filter(s => s.volume)
    .map(s => ({
      date: new Date(s.date).toLocaleDateString("es-ES", { day: "2-digit", month: "short" }),
      volume: s.volume,
    }))
    .reverse();

  const strengthData = sessions
    .filter(s => s.exercises_completed?.length > 0)
    .map(s => ({
      date: new Date(s.date).toLocaleDateString("es-ES", { day: "2-digit", month: "short" }),
      exercises: s.exercises_completed.length,
    }))
    .reverse();

  const activePlan = workoutPlans.find(p => p.status === "active");
  const totalWorkouts = sessions.length;
  const avgIntensity = sessions.length > 0
    ? Math.round(
        sessions.reduce((sum, s) => {
          const intensityScore = {
            light: 3,
            moderate: 5,
            intense: 8,
            very_intense: 10,
          };
          return sum + (intensityScore[s.intensity_level] || 0);
        }, 0) / sessions.length
      )
    : 0;

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-indigo-900 to-purple-900 pb-24">
      <div className="max-w-2xl mx-auto px-4 pt-6">
        <div className="flex items-center gap-3 mb-6">
          <button
            onClick={() => navigate(createPageUrl('Home'))}
            className="p-2 rounded-xl bg-white/10 hover:bg-white/20 transition-colors"
          >
            <ArrowLeft size={20} className="text-white" />
          </button>
          <div>
            <h1 className="text-2xl font-black text-white">{t('your_ai_trainer') || 'Your AI Trainer'}</h1>
            <p className="text-white/60 text-sm">{t('adaptive_plans_tracking') || 'Adaptive plans and smart tracking'}</p>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-3 gap-3 mb-6">
          <div className="bg-white/10 backdrop-blur-xl rounded-2xl p-4 border border-white/20">
            <p className="text-white/60 text-xs mb-1">{t('workouts') || 'Workouts'}</p>
            <p className="text-white text-3xl font-bold">{totalWorkouts}</p>
          </div>
          <div className="bg-white/10 backdrop-blur-xl rounded-2xl p-4 border border-white/20">
            <p className="text-white/60 text-xs mb-1">{t('avg_intensity') || 'Avg Intensity'}</p>
            <p className="text-white text-3xl font-bold">{avgIntensity}</p>
          </div>
          <div className="bg-white/10 backdrop-blur-xl rounded-2xl p-4 border border-white/20">
            <p className="text-white/60 text-xs mb-1">{t('active_plans') || 'Active Plans'}</p>
            <p className="text-white text-3xl font-bold">{workoutPlans.filter(p => p.status === "active").length}</p>
          </div>
        </div>

        {/* Volume Progress */}
        {volumeData.length > 0 && (
          <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-6 border border-white/20 mb-6">
            <h3 className="text-white font-bold mb-4 flex items-center gap-2">
              <TrendingUp size={18} />
              {t('volume_progression') || 'Volume Progression'}
            </h3>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={volumeData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                <XAxis dataKey="date" stroke="rgba(255,255,255,0.5)" style={{ fontSize: 12 }} />
                <YAxis stroke="rgba(255,255,255,0.5)" style={{ fontSize: 12 }} />
                <Tooltip contentStyle={{ backgroundColor: "rgba(15, 23, 42, 0.95)", border: "1px solid rgba(255,255,255,0.2)" }} />
                <Line type="monotone" dataKey="volume" stroke="#10b981" strokeWidth={3} dot={{ fill: "#10b981", r: 4 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* Active Plan */}
        {activePlan && (
          <div className="bg-gradient-to-br from-indigo-500/20 to-purple-500/20 backdrop-blur-xl rounded-3xl p-6 border border-indigo-500/30 mb-6">
            <div className="flex items-start justify-between mb-4">
              <div>
                <h3 className="text-white font-bold text-lg">{activePlan.plan_name}</h3>
                <p className="text-indigo-200 text-sm">
                  {t('week_of') || 'Week'} {activePlan.current_week} {t('of')} {activePlan.duration_weeks}
                </p>
              </div>
              <div className="px-3 py-1 bg-indigo-500/30 border border-indigo-500/50 rounded-full text-indigo-300 text-xs font-bold">
                {activePlan.days_per_week}x/{t('week') || 'week'}
              </div>
            </div>
            <Button
              onClick={() => navigate(`${createPageUrl('WorkoutTracker')}?planId=${activePlan.id}`)}
              className="w-full bg-gradient-to-r from-indigo-500 to-purple-500 hover:from-indigo-600 hover:to-purple-600 text-white font-bold"
            >
              <Dumbbell size={18} className="mr-2" />
              {t('log_workout') || 'Log Workout'}
            </Button>
          </div>
        )}

        {/* Generate New Plan */}
        <div className="bg-white/10 backdrop-blur-xl rounded-3xl p-6 border border-white/20 mb-6">
          <h3 className="text-white font-bold mb-4 flex items-center gap-2">
            <Zap size={18} />
            {t('generate_plan_ai') || 'Generate Plan with AI'}
          </h3>
          <div className="grid grid-cols-2 gap-3">
            {["strength", "hypertrophy", "endurance", "mixed"].map((focus) => (
              <Button
                key={focus}
                onClick={() =>
                  generatePlanMutation.mutate({
                    focus,
                    duration_weeks: 12,
                    days_per_week: 4,
                  })
                }
                disabled={generatePlanMutation.isPending}
                className="bg-white/10 hover:bg-white/20 text-white border border-white/20"
              >
                {focus === "strength" && "💪 " + (t('strength') || 'Strength')}
                {focus === "hypertrophy" && "🏋️ " + (t('hypertrophy') || 'Hypertrophy')}
                {focus === "endurance" && "🏃 " + (t('endurance') || 'Endurance')}
                {focus === "mixed" && "⚡ " + (t('mixed') || 'Mixed')}
              </Button>
            ))}
          </div>
        </div>

        {/* Plans History */}
        <div className="space-y-3">
          <h3 className="text-white font-bold flex items-center gap-2">
            <Calendar size={18} />
            {t('my_plans') || 'My Plans'}
          </h3>
          {workoutPlans.length === 0 ? (
            <div className="bg-white/10 backdrop-blur-xl rounded-2xl p-6 border border-white/20 text-center">
              <Dumbbell size={32} className="text-white/30 mx-auto mb-2" />
              <p className="text-white/70">{t('create_first_plan') || 'Create your first workout plan'}</p>
            </div>
          ) : (
            workoutPlans.map((plan) => (
              <div
                key={plan.id}
                className={`bg-white/10 backdrop-blur-xl rounded-2xl p-4 border transition-all ${
                  plan.status === "active"
                    ? "border-indigo-500/50 bg-indigo-500/10"
                    : "border-white/20"
                }`}
              >
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-white font-bold">{plan.plan_name}</p>
                    <p className="text-white/60 text-sm">{plan.focus} • {plan.days_per_week}x/{t('week') || 'week'}</p>
                  </div>
                  {plan.status !== "active" && (
                    <Button
                      size="sm"
                      onClick={() => activatePlanMutation.mutate(plan.id)}
                      className="bg-indigo-500 hover:bg-indigo-600 text-white"
                    >
                      {t('activate') || 'Activate'}
                    </Button>
                  )}
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}